audit_header: false
title: Todd Martin Real Estate Training Blog
description: If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Todd Martin
  license:
  about_markdown: |
    Todd Martin has over 10 years a experience as a Realtor in the Lousiville area. Over the years, he has gathered statistics and stories that have helped him to grow as an agent and still influence how he does business today. He is a member of the Professional Standards Committee and the Louisville Board of Realtors and is dedicated to mastering his profession by offering 100% customer service to each and every client.

    Todd wants to help you navigate the real estate market by putting his professional knowledge, expertise, and skills to work. He is always striving to get better, adapting the newest available technology to ensure your home gets maximum exposure. Todd has been involved in over a million real estate transactions and has developed the skills to help buyers and sellers save and get the most money out of their transaction. If you want an agent that will devote his full time and attention to each and every one of your specific needs, Todd is your man.
  market: Louisville
  brand: Todd Martin Group
  brokerage: Re/MAX Metro
  address: 1829 Bardstown Rd.<br>Louisville, KY 40204
  phone: 502.220.4663
  email: contact@mooserllc.com
  url: findlouisvillelistings.realgeeks.com
  first_CTA_text:
  first_CTA_URL:
  second_CTA_text: Contact
  second_CTA_URL: '#contact'
  VR_form:
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/remaxlouisville
  linkedin_url: https://www.linkedin.com/in/toddmartinrealtor
  gplus_url: https://plus.google.com/u/0/103473045133901662357
  youtube_url: https://www.youtube.com/channel/UCTEHQ7N9axuLzXvL7nLSdZA
  twitter_url: https://twitter.com/RemaxToddinKY
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/louisville.realtor
  trulia_url: http://www.trulia.com/profile/toddmartin/
  yelp_url: http://www.yelp.com/biz/todd-martin-realtor-louisville
  podcast_url:
podcast:
  title:
  categories: News & Politics
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
images:
  client_headshot_path: '/img/headshot.jpg'
  hero_logo_path: '/img/logo-white.png'
  hero_text: Real Estate Training Blog
  hero_background_hex: '#258eb3'
  hero_image_path: '/img/background.jpg'
brand_color: '#258eb3'
theme_color: '#258eb3'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
