audit_header: false
title: Base Template
description: If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Todd Martin
  license:
  about_markdown: |

  market: Louisville
  brand: Todd Martin Group
  brokerage: Re/MAX Metro
  address: 1829 Bardstown Rd.<br>Louisville, KY 40204
  phone: 502.220.4663
  email: contact@mooserllc.com
  url: findlouisvillelistings.realgeeks.com/
  first_CTA_text:
  first_CTA_URL:
  second_CTA_text: Contact
  second_CTA_URL: '#contact' 
  VR_form:
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title:
  categories: News & Politics
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
images:
  client_headshot_path: 'http://placehold.it/200x200'
  hero_logo_path: '/img/logo-white.png'
  hero_text: Real Estate Video Blog
  hero_background_hex: '#258eb3'
  hero_image_path: '/img/background.jpg'
brand_color: '#258eb3'
theme_color: '#258eb3'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
