---
audit_header: false
title: Louisville Real Estate Video Blog
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from Amped Property Group your professional
  Louisville Real Estate resource.
show_custom_links: true
custom_links:
  - title: Book an Appointment
    url: /book-an-appointment/
client:
  name: Todd Martin
  license:
  about_markdown: >-
    I have been in real estate for over 19 years. After owning an
    &nbsp;international real estate franchise for several years I realized that
    I could take better care of my clients and customers at the local level.
    With past experience in corporate america combined with 26yrs of service in
    the military (Navy, Army and Air Force) this seemed like the right move. I
    decided to open my real estate company and base the company on the highest
    level of customer service possible.&nbsp;


    Over the years I have discovered that real estate is more than business. it
    is about life, whether you are starting out, moving up or simply settling
    down everyone I have ever had the pleasure of working with is in a different
    place in life. I understand and&nbsp; strive to make each experience unique
    and as meaningful as possible.
  market: Louisville
  brand: Amped Property Group
  brokerage: Call It Closed International Realty
  address: '3418 Frankfort Ave Suite 265<br>Louisville, KY 40207'
  phone: 502.200.1980
  email: todd@ampedpg.com
  url: 'https://www.ampedpg.com'
  first_CTA_text:
  first_CTA_URL:
  second_CTA_text: Contact
  second_CTA_URL: '#contact'
emma_form:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/ampedpropertygroup'
  linkedin_url: 'https://www.linkedin.com/in/toddmartinrealtor'
  gplus_url: >-
    https://www.google.com/search?q=amped+realty+louisville+ky&oq=amped+realty+louisville+ky&aqs=chrome..69i57j0j69i60l3.7399j0j7&sourceid=chrome&ie=UTF-8#lrd=0x88690cb0acdef067:0xda3b1ff93d3fa614,1,,,
  youtube_url: 'https://www.youtube.com/channel/UCTEHQ7N9axuLzXvL7nLSdZA'
  twitter_url: 'https://twitter.com/amped_pg'
  instagram_url: 'https://www.instagram.com/ampedatcallitclosed'
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: >-
    https://itunes.apple.com/us/podcast/todd-martin-real-estate-podcast/id1309682579?mt=2
podcast:
  title: Todd Martin Real Estate Careers and Training Podcast
  categories:
    - Education
  image: /uploads/amped-realty-logo-white-030620032109.png
  subtitle: Boost your Career with Veteran Real Estate Agent Todd Martin
  description: >-
    A Podcast about Louisville Real Estate; It's industry, and the people
    working in it. Whether you're just starting out, aspiring to begin, or been
    working in the field for a few years, tune in to get updates, tips, tricks
    and more!
  keywords: >-
    Louisville Real Estate, Real Estate Careers, Real Estate Professionals,
    Realtors, Real estate industry, how much do realtors make
  author: Todd Martin
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /uploads/amped-property-group-logo---red-white.png
  hero_text: Louisville Real Estate Blog
  hero_background_hex: '#990000'
  hero_image_path: /img/background.jpg
brand_color: '#C8102E'
theme_color: '#7A7777'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
---