audit_header: false
title: Louisville Real Estate Video Blog
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
  -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Todd Martin
  license:
  about_markdown: Bio
  market: Louisville
  brand: Amped Realty
  brokerage:
  address: '1829 Bardstown Rd.<br>Louisville, KY 40204'
  phone: 502.220.1980
  email: todd@ampedrealty.com
  url: 'http://www.ampedrealty.com/'
  first_CTA_text:
  first_CTA_URL:
  second_CTA_text: Contact
  second_CTA_URL: '#contact'
emma_form: >-
  <script
  id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808046';</script><script
  src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/ampedrealty/?ref=py_c'
  linkedin_url: 'https://www.linkedin.com/in/toddmartinrealtor'
  gplus_url: 'https://plus.google.com/u/0/103473045133901662357'
  youtube_url: 'https://www.youtube.com/channel/UCTEHQ7N9axuLzXvL7nLSdZA'
  twitter_url: 'https://twitter.com/ToddMartinMetro'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/louisville.realtor'
  trulia_url: 'http://www.trulia.com/profile/toddmartin/'
  yelp_url: 'http://www.yelp.com/biz/todd-martin-realtor-louisville'
  podcast_url: >-
    https://itunes.apple.com/us/podcast/todd-martin-real-estate-podcast/id1309682579?mt=2
podcast:
  title: Todd Martin Real Estate Careers and Training Podcast
  categories:
    - Education
  image: /img/17725lg.png
  subtitle: Boost your Career with Veteran Real Estate Agent Todd Martin
  description: >-
    A Podcast about Louisville Real Estate; It's industry, and the people
    working in it. Whether you're just starting out, aspiring to begin, or been
    working in the field for a few years, tune in to get updates, tips, tricks
    and more!
  keywords: >-
    Louisville Real Estate, Real Estate Careers, Real Estate Professionals,
    Realtors, Real estate industry, how much do realtors make
  author: Todd Martin
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /uploads/17725lg.png
  hero_text: Louisville Real Estate Blog
  hero_background_hex: '#990000'
  hero_image_path: /img/background.jpg
brand_color: '#990000'
theme_color: '#990000'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'